#!/usr/bin/env python3
import os
import sqlite3
import sys
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd


# DB Path
DB_URL = os.environ.get("DB_URL", "user_data/tradesv3.sqlite")
REPORTS_DIR = "user_data/reports"


def get_db_connection():
    db_path = Path(DB_URL)
    if not db_path.exists():
        # Maybe it's a relative path to repo root
        db_path = Path.cwd() / DB_URL
        if not db_path.exists():
             print(f"Database not found at {DB_URL}")
             sys.exit(1)
    return sqlite3.connect(str(db_path))


def generate_report():
    conn = get_db_connection()

    # Query last 24h closed trades
    query = """
    SELECT * FROM trades
    WHERE close_date >= datetime('now', '-1 day')
    AND is_open = 0
    """

    try:
        df = pd.read_sql_query(query, conn)
    except Exception as e:
        print(f"Error querying DB: {e}")
        # Probably empty DB or no table
        conn.close()
        sys.exit(0)

    conn.close()

    # Ensure reports dir
    Path(REPORTS_DIR).mkdir(parents=True, exist_ok=True)

    date_str = datetime.now(UTC).strftime("%Y-%m-%d")
    report_file = f"{REPORTS_DIR}/daily_summary_{date_str}.md"

    with Path(report_file).open("w") as f:
        f.write(f"# Daily Trading Report ({date_str})\n\n")

        if df.empty:
            f.write("No closed trades in the last 24 hours.\n")
            print(f"Report written to {report_file} (Empty)")
            return

        # Preprocessing
        if "close_date" in df.columns:
            df["close_date"] = pd.to_datetime(df["close_date"])
        if "open_date" in df.columns:
            df["open_date"] = pd.to_datetime(df["open_date"])

        # Metrics
        total_trades = len(df)
        wins = df[df["close_profit"] > 0]
        win_rate = (len(wins) / total_trades) * 100
        avg_return = df["close_profit"].mean() * 100
        total_profit_abs = df["close_profit_abs"].sum()

        # Approx Max Drawdown (from closed trades sequence)
        df["cum_profit"] = df["close_profit_abs"].cumsum()
        df["peak"] = df["cum_profit"].cummax()
        df["drawdown"] = df["cum_profit"] - df["peak"]
        max_drawdown = df["drawdown"].min()

        # Exposure Time
        if "close_date" in df.columns and "open_date" in df.columns:
            df["duration"] = df["close_date"] - df["open_date"]
            avg_duration = df["duration"].mean()
            # Format duration
            avg_duration_str = str(avg_duration).split('.')[0] # Remove microseconds
        else:
            avg_duration_str = "N/A"

        f.write("## Performance Summary\n")
        f.write(f"- **Total Trades**: {total_trades}\n")
        f.write(f"- **Win Rate**: {win_rate:.2f}%\n")
        f.write(f"- **Avg Return**: {avg_return:.2f}%\n")
        f.write(f"- **Total Profit (Abs)**: {total_profit_abs:.4f}\n")
        f.write(f"- **Max Drawdown (Approx)**: {max_drawdown:.4f}\n")
        f.write(f"- **Avg Exposure Time**: {avg_duration_str}\n\n")

        f.write("## Top Pairs\n")
        top_pairs = df["pair"].value_counts().head(5)
        for pair, count in top_pairs.items():
            # Get profit for this pair
            pair_profit = df[df["pair"] == pair]["close_profit_abs"].sum()
            f.write(f"- **{pair}**: {count} trades, Profit: {pair_profit:.4f}\n")
        f.write("\n")

        f.write("## Exit Reasons\n")
        if "exit_reason" in df.columns:
            top_reasons = df["exit_reason"].value_counts().head(5)
            for reason, count in top_reasons.items():
                f.write(f"- {reason}: {count}\n")
        else:
            f.write("N/A\n")

        f.write("\n_Generated by Daily Report Tool_")

    print(f"Report written to {report_file}")


if __name__ == "__main__":
    generate_report()
