#!/usr/bin/env python3
import os
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd


# DB Path
DB_URL = os.environ.get("DB_URL", "user_data/tradesv3.sqlite")


def get_db_connection():
    if not Path(DB_URL).exists():
        print(f"Database not found at {DB_URL}")
        sys.exit(1)
    return sqlite3.connect(DB_URL)


def generate_report():
    conn = get_db_connection()

    query = """
    SELECT * FROM trades
    WHERE close_date >= datetime('now', '-1 day')
    AND is_open = 0
    """

    try:
        df = pd.read_sql_query(query, conn)
    except Exception as e:
        print(f"Error querying DB: {e}")
        # Fallback to verify table exists
        sys.exit(1)

    conn.close()

    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    report_file = f"user_data/reports/daily_summary_{date_str}.md"

    # Create dir if not exists
    Path(report_file).parent.mkdir(parents=True, exist_ok=True)

    with Path(report_file).open("w") as f:
        f.write(f"# Daily Trading Report ({date_str})\n\n")

        if df.empty:
            f.write("No closed trades in the last 24 hours.\n")
            print(f"Report written to {report_file} (Empty)")
            return

        # Metrics
        total_trades = len(df)
        wins = df[df["close_profit"] > 0]
        win_rate = (len(wins) / total_trades) * 100
        avg_return = df["close_profit"].mean() * 100
        total_profit_abs = df["close_profit_abs"].sum()

        # Duration
        if "open_date" in df.columns and "close_date" in df.columns:
            df["open_date"] = pd.to_datetime(df["open_date"])
            df["close_date"] = pd.to_datetime(df["close_date"])
            df["duration"] = (df["close_date"] - df["open_date"]).dt.total_seconds() / 60
            avg_duration = df["duration"].mean()
        else:
            avg_duration = 0

        # Max Drawdown (Approximate from closed trades)
        # For real max drawdown we need high res data, but we can use cumulative profit min
        df["cum_profit"] = df["close_profit_abs"].cumsum()
        max_drawdown = df["cum_profit"].min() if not df.empty else 0

        f.write("## Summary\n")
        f.write(f"- **Total Trades**: {total_trades}\n")
        f.write(f"- **Win Rate**: {win_rate:.2f}%\n")
        f.write(f"- **Avg Return**: {avg_return:.2f}%\n")
        f.write(f"- **Total Profit**: {total_profit_abs:.4f}\n")
        f.write(f"- **Avg Duration**: {avg_duration:.2f} min\n")
        f.write(f"- **Min Cum Profit (Max DD)**: {max_drawdown:.4f}\n\n")

        f.write("## Top Pairs\n")
        top_pairs = df["pair"].value_counts().head(5)
        for pair, count in top_pairs.items():
            f.write(f"- {pair}: {count} trades\n")
        f.write("\n")

        f.write("## Top Exit Reasons\n")
        top_reasons = df["exit_reason"].value_counts().head(5)
        for reason, count in top_reasons.items():
            f.write(f"- {reason}: {count}\n")
        f.write("\n")

        if "strategy" in df.columns:
            f.write("## Top Strategies\n")
            top_strats = df["strategy"].value_counts().head(5)
            for strat, count in top_strats.items():
                f.write(f"- {strat}: {count} trades\n")

        f.write("\n_Generated by Daily Report Tool_")

    print(f"Report written to {report_file}")


if __name__ == "__main__":
    generate_report()
